const STORAGE_KEY='pieces-of-this-chapter-messages';
const WELCOME_CONFETTI_KEY='paragon-welcome-confetti';
const seedMessages=[];
const $=s=>document.querySelector(s);
let sharedMessages=null;
let lastSubmissionAt=0;
function localMessages(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(saved)?saved:seedMessages}catch{return seedMessages}}
function saveLocal(messages){localStorage.setItem(STORAGE_KEY,JSON.stringify(messages))}
function escapeHTML(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
async function loadRealPhotos(){try{const [pink,portrait]=await Promise.all([fetch('/images/paragon-pink.b64',{cache:'no-store'}).then(r=>r.text()),fetch('/images/portrait-current.b64',{cache:'no-store'}).then(r=>r.text())]);const pinkSrc=`data:image/jpeg;base64,${pink.trim()}`,portraitSrc=`data:image/jpeg;base64,${portrait.trim()}`;document.querySelectorAll('img[src="/images/paragon-pink.svg"]').forEach(img=>img.src=pinkSrc);document.querySelectorAll('img[src="/images/portrait-current.svg"]').forEach(img=>img.src=portraitSrc)}catch(error){console.warn('Photo assets could not be loaded',error)}}
function render(messages){const wall=$('#memoryWall'),empty=$('#emptyState');$('#messageCount').textContent=messages.length;if(!messages.length){wall.innerHTML='';empty.style.display='block';return}empty.style.display='none';wall.innerHTML=messages.map(m=>`<article class="memory-card"><div class="memory-top"><div><div class="memory-name">${escapeHTML(m.name)}</div><div class="memory-relation">${escapeHTML(m.relation)}</div></div><div class="memory-mood">${escapeHTML(m.mood||'💌')}</div></div><div class="memory-message">“${escapeHTML(m.message)}”</div><div class="memory-date">${escapeHTML(m.date||'Just now')}</div></article>`).join('')}
function setStatus(text,type=''){const el=$('#formStatus');el.textContent=text;el.className=`form-status ${type}`}
async function loadMessages(){try{const response=await fetch('/api/messages',{cache:'no-store'});if(!response.ok)throw new Error('API unavailable');sharedMessages=await response.json();render(sharedMessages)}catch{sharedMessages=null;render(localMessages())}}
async function addMessage(message){const response=await fetch('/api/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(message)});if(!response.ok){let detail='The guestbook could not save your message. Please try again.';try{const data=await response.json();if(data.error)detail=data.error}catch{}throw new Error(detail)}return response.json()}
function welcomeConfetti(){if(sessionStorage.getItem(WELCOME_CONFETTI_KEY))return;sessionStorage.setItem(WELCOME_CONFETTI_KEY,'1');const layer=document.createElement('div');layer.className='welcome-confetti';layer.setAttribute('aria-hidden','true');const pieces=['✦','✧','♡','·','✦','🤎'];for(let i=0;i<20;i++){const piece=document.createElement('span');piece.textContent=pieces[i%pieces.length];piece.style.left=`${Math.random()*100}%`;piece.style.animationDelay=`${Math.random()*0.35}s`;piece.style.setProperty('--drift',`${(Math.random()-.5)*90}px`);piece.style.setProperty('--rotate',`${(Math.random()-.5)*70}deg`);layer.appendChild(piece)}document.body.appendChild(layer);setTimeout(()=>layer.remove(),1800)}
function openQR(){const modal=$('#qrModal'),box=$('#qrcode');modal.classList.add('open');modal.setAttribute('aria-hidden','false');box.innerHTML='';new QRCode(box,{text:location.href.split('#')[0],width:190,height:190,colorDark:'#25221e',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.H})}
function closeQR(){$('#qrModal').classList.remove('open');$('#qrModal').setAttribute('aria-hidden','true')}
$('#guestForm').addEventListener('submit',async e=>{e.preventDefault();const name=$('#guestName').value.trim(),relation=$('#guestRelation').value.trim(),message=$('#guestMessage').value.trim(),mood=$('#guestMood').value,website=$('#guestWebsite').value.trim();if(website)return;if(!name){$('#guestName').focus();setStatus('Please enter your name.','error');return}if(!relation){$('#guestRelation').focus();setStatus('Please tell us how you know Victory.','error');return}if(!message){$('#guestMessage').focus();setStatus('Please write a message before adding your piece.','error');return}if(Date.now()-lastSubmissionAt<10000){setStatus('Take a little moment — your piece has just been added. ✦','error');return}const button=e.submitter;button.disabled=true;button.textContent='Adding your piece…';setStatus('Saving your message…');try{const saved=await addMessage({name,relation,message,mood,website});lastSubmissionAt=Date.now();sharedMessages=sharedMessages||[];sharedMessages.unshift(saved);render(sharedMessages);e.target.reset();setStatus('Your piece is now part of my story. ✦','success');$('#wall-title').scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>setStatus(''),5000)}catch(error){setStatus(error.message,'error')}finally{button.disabled=false;button.textContent='Add my piece ✦'}});
['#openQrTop','#openQrHero','#openQrBottom'].forEach(id=>$(id).addEventListener('click',openQR));
$('#closeQr').addEventListener('click',closeQR);document.querySelector('[data-close-qr]').addEventListener('click',closeQR);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeQR()});
$('#copyLink').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href.split('#')[0]);$('#copyStatus').textContent='Link copied — share it with your people ✦'}catch{$('#copyStatus').textContent='Copy failed. You can copy the address from your browser.'}});
if(!sessionStorage.getItem(WELCOME_CONFETTI_KEY))welcomeConfetti();
loadRealPhotos();
loadMessages();