const STORAGE_KEY='pieces-of-this-chapter-messages';
const seedMessages=[];
const $=s=>document.querySelector(s);
let sharedMessages=null;
function localMessages(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(saved)?saved:seedMessages}catch{return seedMessages}}
function saveLocal(messages){localStorage.setItem(STORAGE_KEY,JSON.stringify(messages))}
function escapeHTML(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
function render(messages){const wall=$('#memoryWall'),empty=$('#emptyState');$('#messageCount').textContent=messages.length;if(!messages.length){wall.innerHTML='';empty.style.display='block';return}empty.style.display='none';wall.innerHTML=messages.map(m=>`<article class="memory-card"><div class="memory-top"><div><div class="memory-name">${escapeHTML(m.name)}</div><div class="memory-relation">${escapeHTML(m.relation)}</div></div><div class="memory-mood">${escapeHTML(m.mood||'💌')}</div></div><div class="memory-message">“${escapeHTML(m.message)}”</div><div class="memory-date">${escapeHTML(m.date||'Just now')}</div></article>`).join('')}
function setStatus(text,type=''){const el=$('#formStatus');el.textContent=text;el.className=`form-status ${type}`}
async function loadMessages(){try{const response=await fetch('/api/messages',{cache:'no-store'});if(!response.ok)throw new Error('API unavailable');sharedMessages=await response.json();render(sharedMessages)}catch{sharedMessages=null;render(localMessages())}}
async function addMessage(message){const response=await fetch('/api/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(message)});if(!response.ok){let detail='The guestbook could not save your message. Please try again.';try{const data=await response.json();if(data.error)detail=data.error}catch{}throw new Error(detail)}return response.json()}
function openQR(){const modal=$('#qrModal'),box=$('#qrcode');modal.classList.add('open');modal.setAttribute('aria-hidden','false');box.innerHTML='';new QRCode(box,{text:location.href.split('#')[0],width:190,height:190,colorDark:'#25221e',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.H})}
function closeQR(){$('#qrModal').classList.remove('open');$('#qrModal').setAttribute('aria-hidden','true')}
$('#guestForm').addEventListener('submit',async e=>{e.preventDefault();const name=$('#guestName').value.trim(),relation=$('#guestRelation').value.trim(),message=$('#guestMessage').value.trim(),mood=$('#guestMood').value;if(!name){$('#guestName').focus();setStatus('Please enter your name.','error');return}if(!relation){$('#guestRelation').focus();setStatus('Please tell us how you know Victory.','error');return}if(!message){$('#guestMessage').focus();setStatus('Please write a message before adding your piece.','error');return}const button=e.submitter;button.disabled=true;button.textContent='Adding your piece…';setStatus('Saving your message…');try{const saved=await addMessage({name,relation,message,mood});sharedMessages=sharedMessages||[];sharedMessages.unshift(saved);render(sharedMessages);e.target.reset();setStatus('Your piece has been added ✦','success');$('#wall-title').scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>setStatus(''),4500)}catch(error){setStatus(error.message,'error')}finally{button.disabled=false;button.textContent='Add my piece ✦'}});
['#openQrTop','#openQrHero','#openQrBottom'].forEach(id=>$(id).addEventListener('click',openQR));
$('#closeQr').addEventListener('click',closeQR);document.querySelector('[data-close-qr]').addEventListener('click',closeQR);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeQR()});
$('#copyLink').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href.split('#')[0]);$('#copyStatus').textContent='Link copied — share it with your people ✦'}catch{$('#copyStatus').textContent='Copy failed. You can copy the address from your browser.'}});
$('#clearDemo').addEventListener('click',()=>{if(confirm('Reset the local wall? This only affects this browser.')){localStorage.removeItem(STORAGE_KEY);sharedMessages=null;render([])}});
loadMessages();